import assert from 'node:assert/strict';
import {writeFileSync,mkdirSync} from 'node:fs';
import {join} from 'node:path';
import {pathToFileURL} from 'node:url';
import {compileProject} from './test-support.mjs';
const project=compileProject({name:'signs',api:true});
const names=['window','Image','requestAnimationFrame','cancelAnimationFrame','localStorage','setTimeout','clearTimeout'],original=new Map(names.map(k=>[k,Object.getOwnPropertyDescriptor(globalThis,k)])),realNow=Date.now;
let checks=0,failures=0;
try{
 const [sim,str,delta,{GameClient}]=await Promise.all(['simulation','structures','world-delta','client'].map(name=>import(project.module(name))));
 const route=await import(project.route());let now=100000;Date.now=()=>now;
 const clone=structuredClone,X=260,Y=320,ID=str.buildingKey(X,Y,'sign'),token='sign-test-token',otherToken='sign-other-token';
 const hash=async s=>Buffer.from(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s))).toString('hex'),secret=await hash(token),otherSecret=await hash(otherToken);
 const input=(seq,commands=[])=>({seq,dx:0,dy:0,movements:[],commands});
 function fixture(){const s=sim.createWorld(now);s.mobs=[];s.players={p:sim.createPlayer('p',secret,'P',0,now),q:sim.createPlayer('q',otherSecret,'Q',1,now)};for(const p of Object.values(s.players)){p.x=X+.5;p.y=Y-1;}s.buildings={[ID]:{id:ID,x:X,y:Y,kind:'sign'}};s.plots={};return{s,p:s.players.p,q:s.players.q,sign:s.buildings[ID]};}
 function write(f,text,extra={},who='p'){return sim.applyInput(f.s,who,input(f.s.players[who].seq+1,[{type:'writeSign',target:ID,text,...extra}]),++now);}
 async function test(name,fn){checks++;try{await fn();console.log('PASS',name);}catch(e){failures++;console.log('FAIL',name,e.stack);}}
 await test('old buildings without text normalize and round-trip unchanged',()=>{const f=fixture(),before=clone(f.s.buildings);sim.normalizeWorld(f.s,now);assert.deepEqual(f.s.buildings,before);assert.deepEqual(JSON.parse(JSON.stringify(f.s)).buildings,before);});
 await test('240 Chinese characters persist exactly and 241 are rejected without changing saved text',()=>{const f=fixture(),text='林'.repeat(240);assert.equal(write(f,text),null);assert.equal(f.sign.text,text);assert.equal(write(f,text+'间'),'最多240字');assert.equal(f.sign.text,text);});
 await test('240 astral characters count as Unicode code points without cutting surrogate pairs',()=>{const f=fixture(),text='🌲'.repeat(240);assert.equal(write(f,text),null);assert.equal(f.sign.text,text);assert.equal(write(f,text+'🌲'),'最多240字');assert.equal(Array.from(f.sign.text).length,240);});
 await test('CRLF and tabs normalize; C0/C1/bidi control characters are stripped',()=>{const f=fixture();assert.equal(write(f,'林\r\n间\r小\t筑\u0000\u0007\u001b\u007f\u0085\u202e\u2066\ufeff'),null);assert.equal(f.sign.text,'林\n间\n小 筑');});
 await test('blank content is allowed and does not remove the sign',()=>{const f=fixture();write(f,'已有文字');assert.equal(write(f,''),null);assert.equal(f.sign.text,'');assert.equal(f.sign.kind,'sign');});
 await test('markup remains plain text and never enters building structure or prototype',()=>{const f=fixture(),text='<img src=x onerror=alert(1)>\n<script>bad()</script>';write(f,text);assert.equal(f.sign.text,text);assert.deepEqual(Object.keys(f.sign).sort(),['id','kind','text','x','y']);assert.equal({}.polluted,undefined);});
 await test('non-string payloads are rejected without coercion',()=>{const f=fixture();for(const text of [undefined,null,12,{},['text']])assert.equal(write(f,text),'告示牌内容无效');assert(!Object.hasOwn(f.sign,'text'));});
 await test('only sign targets can be edited; prototype/missing/foreign targets are rejected',()=>{const f=fixture();for(const kind of ['floor','fence','planter','door','lantern']){f.sign.kind=kind;assert.equal(write(f,'x'),'告示牌不存在');}f.sign.kind='sign';for(const target of ['missing','__proto__','constructor',null,{}])assert.equal(write(f,'x',{target}),'告示牌不存在');assert(!f.sign.text);});
 await test('same-floor distance permits exactly 2.7 tiles and rejects farther or other floors',()=>{const f=fixture();f.p.x=X+.5;f.p.y=Y+.5-2.7;assert.equal(write(f,'边界'),null);f.p.y-=.001;assert.equal(write(f,'远处'),'请靠近同层告示牌');f.p.y=Y-1;f.p.level=1;assert.equal(write(f,'楼上'),'请靠近同层告示牌');assert.equal(f.sign.text,'边界');});
 await test('both room players can edit without resource cost or world side effects',()=>{const f=fixture(),inventory=clone(f.p.inventory),events=clone(f.s.events);write(f,'甲');write(f,'乙',{},'q');assert.equal(f.sign.text,'乙');assert.deepEqual(f.p.inventory,inventory);assert.deepEqual(f.s.events,events);const clean=sim.publicWorld(f.s);assert.equal(clean.buildings[ID].text,'乙');assert.equal(clean.players.p.secret,undefined);});
 class Database{constructor(s){this.row={state:JSON.stringify(s),version:0};this.writes=0;this.conflicts=0;}prepare(sql){return{bind:(...v)=>({first:async()=>v[0]==='SIGNTEST'?{...this.row}:null,run:async()=>{this.writes++;const[state,,room,version]=v;assert(sql.startsWith('UPDATE'));if(room!=='SIGNTEST'||version!==this.row.version){this.conflicts++;return{meta:{changes:0}};}this.row={state,version:version+1};return{meta:{changes:1}};}})}}}
 function http(db,tokenValue,seq,text,extra={}){globalThis.__networkTestDb=db;return route.POST(new Request('https://game.test/api/game',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'sync',room:'SIGNTEST',token:tokenValue,protocol:2,poll:true,input:input(seq,text===undefined?[]:[{type:'writeSign',target:ID,text}]),...extra})}));}
 await test('real protocol2 route authenticates, persists and returns shared sign text',async()=>{const f=fixture(),db=new Database(f.s);let res=await http(db,token,1,'大家好');assert.equal(res.status,200);assert.equal((await res.json()).state.buildings[ID].text,'大家好');assert.equal(JSON.parse(db.row.state).buildings[ID].text,'大家好');res=await http(db,otherToken,1,'欢迎');assert.equal(res.status,200);assert.equal(JSON.parse(db.row.state).buildings[ID].text,'欢迎');});
 await test('invalid token and foreign room cannot write signs',async()=>{const f=fixture(),db=new Database(f.s);assert.equal((await http(db,'invalid',1,'bad')).status,403);assert.equal((await http(db,token,1,'bad',{room:'OTHERROM'})).status,404);assert.equal(db.writes,0);assert(!JSON.parse(db.row.state).buildings[ID].text);});
 await test('concurrent shared edits use CAS and persist one whole submitted text',async()=>{const db=new Database(fixture().s),results=await Promise.all([http(db,token,1,'甲'.repeat(120)),http(db,otherToken,1,'乙'.repeat(120))]);assert.deepEqual(results.map(r=>r.status),[200,200]);assert.equal(db.row.version,2);assert.equal(db.writes-db.conflicts,2);const saved=JSON.parse(db.row.state);assert(['甲'.repeat(120),'乙'.repeat(120)].includes(saved.buildings[ID].text));assert.equal(saved.players.p.seq,1);assert.equal(saved.players.q.seq,1);});
 await test('retried input sequence cannot revert another player’s more recent edit',async()=>{const db=new Database(fixture().s);await http(db,token,1,'first');await http(db,otherToken,1,'newer');await http(db,token,1,'first');assert.equal(JSON.parse(db.row.state).buildings[ID].text,'newer');assert.equal(db.row.version,2);});
 await test('sign content updates and removal reconstruct through protocol2 delta without secrets',async()=>{const db=new Database(fixture().s),first=await(await http(db,token,1)).json(),second=await(await http(db,token,2,'增量内容',{sinceVersion:first.version})).json();assert(second.delta);const rebuilt=delta.applyWorldDelta(first.state,second.delta);assert.equal(rebuilt.buildings[ID].text,'增量内容');assert.deepEqual(rebuilt,sim.publicWorld(JSON.parse(db.row.state)));assert(!JSON.stringify(second).includes(secret));const next=clone(rebuilt);delete next.buildings[ID];assert.deepEqual(delta.applyWorldDelta(rebuilt,delta.worldDelta(rebuilt,next,second.version)),next);});
 globalThis.window={addEventListener(){},removeEventListener(){}};globalThis.Image=class{};globalThis.requestAnimationFrame=()=>1;globalThis.cancelAnimationFrame=()=>{};globalThis.setTimeout=()=>1;globalThis.clearTimeout=()=>{};Object.defineProperty(globalThis,'localStorage',{configurable:true,value:{getItem:()=>null,setItem(){}}});
 function clientFixture(){const f=fixture(),opens=[],canvas={addEventListener(){},removeEventListener(){},getBoundingClientRect:()=>({left:0,top:0,width:800,height:400})},c=new GameClient(canvas,()=>{},()=>{},()=>{},'/api/game',()=>{},id=>opens.push(id));c.connected=true;c.session={room:'SIGNTEST',playerId:'p',token};c.world=f.s;c.pos={x:f.p.x,y:f.p.y,face:'down',level:0,moving:false};c.flushActions=()=>{};c.loadLayout();return{...f,c,opens};}
 const key=(key,extra={})=>({key,repeat:false,target:{matches:()=>false},preventDefault(){},...extra});
 await test('F opens a nearby sign locally, pauses controls and sends no command',()=>{const f=clientFixture();try{f.c.held=true;f.c.keys.add('w');f.c.keyDown(key('f'));assert.deepEqual(f.opens,[ID]);assert.equal(f.c.commands.length,0);assert.equal(f.c.paused,true);assert.equal(f.c.held,false);assert.equal(f.c.keys.size,0);}finally{f.c.destroy();}});
 await test('F keeps door, stair and mature-crop priority; Shift F stays descend',()=>{for(const kind of ['door','stairs','crop','shift']){const f=clientFixture();try{if(kind==='crop')f.s.plots[`${X}:${Y}`]={x:X,y:Y,crop:'carrot',progress:90,updated:now,wetUntil:0};else if(kind!=='shift'){const id=str.buildingKey(X,Y,kind);f.s.buildings[id]={id,x:X,y:Y,kind};}f.c.keyDown(key('f',{shiftKey:kind==='shift'}));assert.deepEqual(f.opens,[],kind);assert.equal(f.c.commands[0].type,kind==='shift'?'descend':kind==='crop'?'harvest':'interact');if(kind==='crop')assert.equal(f.c.localWork.action,'harvest');}finally{f.c.destroy();}}});
 await test('non-hammer click sign opens reading with empty hand; hammer preserves construction mode',()=>{for(const hammer of [false,true]){const f=clientFixture();try{f.c.pointer={x:X+.5,y:Y+.5};if(hammer)f.c.setTool('build');else f.c.selectSlot(8);f.c.act();assert.deepEqual(f.opens,hammer?[]:[ID]);assert(!f.c.commands.some(c=>c.type==='attack'));}finally{f.c.destroy();}}});
 await test('local read validates sign type, distance, floor, pause and action lock',()=>{for(const condition of ['far','floor','paused','tool','not-sign']){const f=clientFixture();try{if(condition==='far')f.c.pos.x+=10;if(condition==='floor')f.c.pos.level=1;if(condition==='paused')f.c.paused=true;if(condition==='tool')f.c.unconfirmedSwing={type:'attack'};if(condition==='not-sign')f.sign.kind='fence';assert.equal(f.c.readSign(ID),false,condition);assert.deepEqual(f.opens,[]);}finally{f.c.destroy();}}});
 await test('modal save is the only paused command allowed and waits for authoritative acknowledgement',async()=>{const f=clientFixture();try{f.c.readSign(ID);assert.equal(f.c.command({type:'attack',tool:'axe'}),false);assert.equal(f.c.command({type:'writeSign',target:ID,text:'forged'}),false);let settled=false;const result=f.c.saveSign(ID,'已保存').then(v=>{settled=true;return v;});await Promise.resolve();assert.equal(settled,false);assert.equal(f.sign.text,undefined);assert.deepEqual(f.c.commands.map(c=>c.type),['writeSign']);f.c.request=async body=>{const state=clone(f.s);sim.applyInput(state,'p',body.input,++now);return{state,version:1};};await f.c.sync();assert.equal(await result,null);assert.equal(f.c.world.buildings[ID].text,'已保存');}finally{f.c.destroy();}});
 await test('server rejection reaches editor without claiming saved or replacing persisted content',async()=>{const f=clientFixture();try{f.sign.text='原文';f.c.readSign(ID);const result=f.c.saveSign(ID,'未授权新文');f.c.request=async()=>({state:clone(f.s),version:1,message:'请靠近同层告示牌'});await f.c.sync();assert.equal(await result,'请靠近同层告示牌');assert.equal(f.c.world.buildings[ID].text,'原文');}finally{f.c.destroy();}});
 await test('transient network failure keeps one pending save and retries same command exactly once',async()=>{const f=clientFixture();try{f.c.readSign(ID);let settled=false;const result=f.c.saveSign(ID,'重试后保存').then(v=>{settled=true;return v;});f.c.request=async()=>{throw Error('offline');};await f.c.sync();assert.equal(settled,false);assert.equal(f.c.pending.commands.length,1);const id=f.c.pending.commands[0].id;f.c.request=async body=>{assert.equal(body.input.commands[0].id,id);const state=clone(f.s);sim.applyInput(state,'p',body.input,++now);return{state,version:1};};await f.c.sync();assert.equal(await result,null);assert.equal(f.c.world.buildings[ID].text,'重试后保存');assert.equal(f.c.pending,null);}finally{f.c.destroy();}});
 await test('cancel/read-only use sends no edits; removed sign and distant save are blocked',async()=>{const f=clientFixture();try{f.c.readSign(ID);f.c.closeSign();assert.equal(f.c.commands.length,0);assert.equal(await f.c.saveSign(ID,'x'),'请靠近同层告示牌');f.c.paused=false;f.c.readSign(ID);delete f.s.buildings[ID];assert.equal(await f.c.saveSign(ID,'x'),'请靠近同层告示牌');assert.equal(f.c.commands.length,0);}finally{f.c.destroy();}});
 await test('disconnecting releases pending editor save with an explicit error',async()=>{const f=clientFixture();f.c.readSign(ID);const result=f.c.saveSign(ID,'x');f.c.destroy();assert.equal(await result,'已离开世界');});
 mkdirSync(join(project.temp,'components'),{recursive:true});const hostPath=join(project.temp,'components/sign-host.mjs');writeFileSync(hostPath,`export const states=[];let cursor=0;export function reset(){cursor=0;}export function useState(value){const i=cursor++;if(!(i in states))states[i]=value;return[states[i],v=>{states[i]=typeof v==='function'?v(states[i]):v;}];}export function jsx(type,props,key){return{type,props:props||{},key};}export const jsxs=jsx;export const Fragment='fragment';`);
 const host=await import(pathToFileURL(hostPath)),{default:Panel}=await import(project.compileFile('components/SignPanel.tsx',{'react':'./sign-host.mjs','react/jsx-runtime':'./sign-host.mjs'}));
 function nodes(n){if(!n||typeof n!=='object')return[];return[n,...[n.props?.children].flat(8).flatMap(nodes)];}
 function panelFixture(text='欢迎'){host.states.length=0;let closed=0,resolve;const sent=[],props={text,onClose:()=>closed++,onSave:v=>{sent.push(v);return new Promise(r=>{resolve=r;});}};const render=()=>{host.reset();return nodes(Panel(props));},button=label=>render().find(n=>n.type==='button'&&n.props.children===label),area=()=>render().find(n=>n.type==='textarea');return{props,sent,render,button,area,closed:()=>closed,resolve:v=>resolve(v)};}
 const flush=async()=>{for(let i=0;i<5;i++)await Promise.resolve();};
 await test('real SignPanel initially displays saved content as React text, including markup',()=>{const text='<script>alert(1)</script>',f=panelFixture(text),p=f.render().find(n=>n.props.className==='sign-content');assert.equal(p.props.children,text);assert(!f.render().some(n=>n.props.dangerouslySetInnerHTML));assert.equal(f.area(),undefined);assert.deepEqual(f.sent,[]);});
 await test('real SignPanel edit draft cancels without altering saved content or sending a command',()=>{const f=panelFixture('原文');f.button('编辑').props.onClick();assert.equal(f.area().props.value,'原文');f.area().props.onChange({target:{value:'草稿'}});f.button('取消').props.onClick();assert.equal(f.render().find(n=>n.props.className==='sign-content').props.children,'原文');assert.deepEqual(f.sent,[]);f.button('编辑').props.onClick();assert.equal(f.area().props.value,'原文');});
 await test('real SignPanel normalizes controls, checks codepoint limit and permits blank save',async()=>{const f=panelFixture();f.button('编辑').props.onClick();f.area().props.onChange({target:{value:'甲\u0000\r\n乙'}});assert.equal(f.area().props.value,'甲\n乙');f.area().props.onChange({target:{value:'🌲'.repeat(240)}});assert.equal(f.button('保存').props.disabled,false);f.area().props.onChange({target:{value:'甲'.repeat(241)}});assert.equal(f.button('保存').props.disabled,true);f.area().props.onChange({target:{value:''}});f.render().find(n=>n.type==='form').props.onSubmit({preventDefault(){}});assert.deepEqual(f.sent,['']);assert(f.button('保存中…').props.disabled);f.props.text='';f.resolve(null);await flush();assert.equal(f.area(),undefined);});
 await test('real SignPanel keeps edit and error after failed save; second confirmed save shows current text',async()=>{const f=panelFixture();f.button('编辑').props.onClick();f.area().props.onChange({target:{value:'新文'}});f.render().find(n=>n.type==='form').props.onSubmit({preventDefault(){}});f.resolve('距离太远');await flush();assert.equal(f.area().props.value,'新文');assert(f.render().some(n=>n.props.role==='alert'&&n.props.children==='距离太远'));f.render().find(n=>n.type==='form').props.onSubmit({preventDefault(){}});f.props.text='新文';f.resolve(null);await flush();assert.equal(f.render().find(n=>n.props.className==='sign-content').props.children,'新文');});
 await test('real SignPanel blocks gameplay key propagation and closes with Escape without saving',()=>{const f=panelFixture(),e={key:'Escape',preventDefault(){this.prevented=true;},stopPropagation(){this.stopped=true;}};f.render().find(n=>n.type==='section').props.onKeyDown(e);assert.equal(f.closed(),1);assert.equal(e.stopped,true);assert.equal(e.prevented,true);assert.deepEqual(f.sent,[]);});
 console.log(`${checks} checks; ${failures} failure(s)`);process.exitCode=failures?1:0;
}finally{Date.now=realNow;for(const[k,v]of original)if(v)Object.defineProperty(globalThis,k,v);else delete globalThis[k];delete globalThis.__networkTestDb;project.cleanup();}
