import assert from 'node:assert/strict';
import {mkdirSync,writeFileSync} from 'node:fs';
import {join} from 'node:path';
import {pathToFileURL} from 'node:url';
import {compileProject} from './test-support.mjs';
const project=compileProject({name:'loading'}),names=['window','Image','document','fetch','localStorage','requestAnimationFrame','cancelAnimationFrame','setTimeout','clearTimeout'],original=new Map(names.map(k=>[k,Object.getOwnPropertyDescriptor(globalThis,k)]));
let checks=0;const clients=[];
try{
 const assets=await import(project.module('asset-loading'));
 const timers=new Map(),frames=new Map(),storage=new Map(),images=[],listeners=new Map();let id=0,time=10000;
 globalThis.setTimeout=(fn,ms)=>{timers.set(++id,{fn,ms});return id;};globalThis.clearTimeout=id=>timers.delete(id);
 globalThis.requestAnimationFrame=fn=>{frames.set(++id,fn);return id;};globalThis.cancelAnimationFrame=id=>frames.delete(id);
 globalThis.window={addEventListener:(type,fn)=>{if(!listeners.has(type))listeners.set(type,new Set());listeners.get(type).add(fn);},removeEventListener:(type,fn)=>listeners.get(type)?.delete(fn)};
 globalThis.localStorage={getItem:key=>storage.get(key)??null,setItem:(key,value)=>storage.set(key,value)};
 globalThis.Image=class{constructor(){images.push(this);}set src(value){this.url=value;}};
 async function settle(){for(let i=0;i<8;i++)await Promise.resolve();}
 async function paint(){const queue=[...frames];frames.clear();time+=17;for(const[,fn]of queue)fn(time);await settle();}
 async function test(name,run){await run();checks++;console.log('PASS',name);}
 await test('asset manifest counts all distinct source images before either loading batch starts',()=>{const attempt=assets.beginAssets();assert.equal(assets.getAssetLoading().total,new Set(assets.ART_FILES).size);assert(assets.ART_FILES.length>=40);assert.equal(assets.getAssetLoading().loaded,0);assets.loadedAsset(attempt,'/art/'+assets.ART_FILES[0]);assets.loadedAsset(attempt,'/art/'+assets.ART_FILES[0]);assert.equal(assets.getAssetLoading().loaded,1);});
 await test('late image completions from a failed attempt cannot change retry progress',()=>{const old=assets.getAssetLoading().attempt;assets.failAssets(old,Error('fail'));const current=assets.beginAssets();assets.loadedAsset(old,'/art/'+assets.ART_FILES[1]);assert.equal(assets.getAssetLoading().loaded,0);assets.loadedAsset(current,'/art/'+assets.ART_FILES[1]);assert.equal(assets.getAssetLoading().loaded,1);});
 await test('downloaded images still require atlas completion, and incomplete atlases cannot report ready',()=>{const attempt=assets.beginAssets();assert.throws(()=>assets.finishAssets(attempt),/素材准备不完整/);for(const file of assets.ART_FILES)assets.loadedAsset(attempt,'/art/'+file);assert.equal(assets.getAssetLoading().phase,'atlas');assert.equal(assets.assetsReady(),false);assets.finishAssets(attempt);assert.equal(assets.assetsReady(),true);});
 const art=await import(project.module('art'));
 await test('real art loader drops a failed promise so retry starts a fresh image batch',async()=>{images.length=0;const first=art.loadArt();assert.equal(art.loadArt(),first);const started=images.length;assert(started>30);images[0].onerror();await assert.rejects(first,/素材加载失败/);const before=assets.getAssetLoading().attempt;const retry=art.loadArt();assert.notEqual(retry,first);assert.equal(assets.getAssetLoading().attempt,before+1);assert.equal(images.length,started*2);images[started].onerror();await assert.rejects(retry,/素材加载失败/);for(const image of images)image.onerror?.();await settle();assert.equal(assets.getAssetLoading().phase,'error');});
 await test('real image timeout is recoverable and detaches both image callbacks',async()=>{images.length=0;const pending=art.loadArt(),image=images[0],timeout=[...timers.values()].find(v=>v.ms===20000);assert(timeout);timeout.fn();await assert.rejects(pending,/素材加载超时/);assert.equal(image.onload,null);assert.equal(image.onerror,null);for(const other of images)other.onerror?.();await settle();});
 timers.clear();
 const hostPath=join(project.temp,'lib/loading-host.mjs');
 writeFileSync(hostPath,`import {beginAssets,loadedAsset,finishAssets,failAssets,ART_FILES} from './asset-loading.mjs';export const batches=[],draws=[],preparations=[];export let drawError=false;export function setDrawError(v){drawError=v;}export function loadArt(){const attempt=beginAssets();return new Promise((resolve,reject)=>batches.push({resolve:()=>{for(const file of ART_FILES)loadedAsset(attempt,'/art/'+file);finishAssets(attempt);resolve({fire0:{}});},reject:()=>{const e=Error('素材加载失败');failAssets(attempt,e);reject(e);}}));}export async function prepareWorldMap(next,active){preparations.push('start');await next();if(active())preparations.push('done');}export function render(...args){if(drawError)throw Error('场景准备失败');draws.push(args);}export function pointerWorld(){return{x:0,y:0};}export function pickResource(){}export function buildTarget(p){return p;}export class GameAudio{enabled=true;unlock(){}destroy(){}toggle(){}play(){}ambience(){}}`);
 const host=await import(pathToFileURL(hostPath));
 const {GameClient}=await import(project.compileFile('lib/client.ts',{'./art':'./loading-host.mjs','./renderer':'./loading-host.mjs','./audio':'./loading-host.mjs'})),sim=await import(project.module('simulation'));
 function reply(room='LOADROOM'){const state=sim.createWorld(100000);state.players.p=sim.createPlayer('p','secret','P',0,100000);return{room,playerId:'p',token:'secret',state};}
 function fixture(){const notices=[],canvas={addEventListener(){},removeEventListener(){},getBoundingClientRect:()=>({left:0,top:0,width:1000,height:700})},c=new GameClient(canvas,s=>notices.push(s),()=>{},()=>{});clients.push(c);return{c,notices,batch:host.batches.at(-1)};}
 const key={key:'d',target:{matches:()=>false},preventDefault(){},repeat:false};
 await test('connection without ready art cannot move, attack, open inventory or queue held input',async()=>{const{c,batch}=fixture();c.request=async()=>reply();await c.connect('create');assert.equal(c.connected,true);assert.equal(c.playable,false);c.press('d',true);c.keyDown(key);c.pointerDown({button:0,clientX:1,clientY:1,preventDefault(){}});assert.equal(c.keys.size,0);assert.equal(c.held,false);assert.equal(c.command({type:'dodge'}),false);assert.deepEqual(c.movement(),{x:0,y:0});assert(c.loading.completed<c.loading.total);batch.reject();await settle();assert.equal(c.loading.phase,'error');c.destroy();});
 await test('art readiness waits for connection, map preparation and actual first scene draw',async()=>{const{c,batch}=fixture();let finish;c.request=()=>new Promise(resolve=>finish=resolve);const pending=c.connect('create');batch.resolve();await settle();assert.equal(c.loading.phase,'world');assert.equal(c.playable,false);finish(reply());await pending;assert.equal(c.loading.phase,'scene');const drawCount=host.draws.length;assert(c.loading.completed<c.loading.total);for(let i=0;i<5&&!c.ready;i++)await paint();assert.equal(c.ready,true);assert(host.draws.length>drawCount);assert.equal(c.loading.completed,c.loading.total);assert.equal(c.loading.phase,'ready');c.press('d',true);assert.equal(c.keys.has('d'),true);assert(c.movement().x>0);c.destroy();});
 await test('asset retry in a connected room preserves that room and never creates another world',async()=>{const{c,batch}=fixture();let calls=0;c.request=async()=>{calls++;return reply();};await c.connect('create');batch.reject();await settle();await c.retryConnection();assert.equal(calls,1);host.batches.at(-1).resolve();await settle();for(let i=0;i<5&&!c.ready;i++)await paint();assert.equal(c.ready,true);assert.equal(c.session.room,'LOADROOM');c.destroy();});
 await test('first-render failure stays below 100 percent and retries the scene without reconnecting',async()=>{const{c,batch}=fixture();let calls=0;c.request=async()=>{calls++;return reply();};await c.connect('create');host.setDrawError(true);batch.resolve();await settle();for(let i=0;i<5;i++)await paint();assert.equal(c.loading.phase,'error');assert.equal(c.ready,false);assert(c.loading.completed<c.loading.total);host.setDrawError(false);await c.retryConnection();for(let i=0;i<5&&!c.ready;i++)await paint();assert.equal(c.ready,true);assert.equal(calls,1);c.destroy();});
 await test('room changes cancel old preparation and old request replies cannot change the new session',async()=>{const{c,batch}=fixture();let oldReply;c.request=body=>body.room==='OLDROOM1'?new Promise(resolve=>oldReply=resolve):Promise.resolve(reply('NEWROOM2'));const old=c.connect('join','OLDROOM1');batch.resolve();await settle();await c.connect('join','NEWROOM2');oldReply(reply('OLDROOM1'));await old;for(let i=0;i<5&&!c.ready;i++)await paint();assert.equal(c.session.room,'NEWROOM2');assert.equal(c.ready,true);assert(host.draws.at(-1)[4].roomKey==='NEWROOM2');c.destroy();});
 await test('destroy while preparing removes owned frames and late asset resolution produces no state change',async()=>{const{c,batch,notices}=fixture();c.request=async()=>reply();await c.connect('create');const count=notices.length;c.destroy();batch.resolve();await settle();assert.equal(notices.length,count);assert.equal(c.ready,false);assert.equal(c.keys.size,0);assert.equal(c.preparationFrame,0);assert.equal(c.preparationResolve,undefined);assert.equal(c.playable,false);});
 await test('old HTTP timing metadata cannot shift the clock after a new connection generation',async()=>{const{c,batch}=fixture();let finish;globalThis.fetch=()=>new Promise(resolve=>finish=resolve);const pending=c.request({action:'create'});c.generation++;finish({ok:true,json:async()=>({...reply(),networkVersion:2,serverReceivedAt:Date.now()+99999,serverSentAt:Date.now()+99999})});await pending;assert.equal(c.timeOffset,0);batch.reject();await settle();c.destroy();});
 // The fade controller uses a fresh generation and clears its timer on unmount.
 mkdirSync(join(project.temp,'components'),{recursive:true});const uiPath=join(project.temp,'components/loading-ui-host.mjs');writeFileSync(uiPath,`export const states=[],effects=[];let i=0,j=0;export function reset(clear=false){i=j=0;if(clear){states.length=effects.length=0;}}export function useState(v){const n=i++;if(!(n in states))states[n]=v;return[states[n],v=>states[n]=v];}export function useEffect(fn){effects[j++]=fn;}export function jsx(type,props){return{type,props:props||{}};}export const jsxs=jsx;`);
 const ui=await import(pathToFileURL(uiPath)),{default:LoadingScreen,LOADING_FADE_MS}=await import(project.compileFile('components/LoadingScreen.tsx',{'react':'./loading-ui-host.mjs','react/jsx-runtime':'./loading-ui-host.mjs'}));
 const nodes=n=>!n||typeof n!=='object'?[]:[n,...[n.props?.children].flat(5).flatMap(nodes)];
 function screen(loading,extra={}){ui.reset();return LoadingScreen({loading,onRetry(){},onExit(){},...extra});}
 await test('loader exposes actual count progress, explicit retry and a main-menu exit',()=>{ui.reset(true);let retries=0,exits=0;const tree=screen({generation:1,phase:'error',completed:11,total:44,error:'素材加载失败'},{onRetry:()=>retries++,onExit:()=>exits++});assert.equal(nodes(tree).find(n=>n.props.role==='progressbar').props['aria-valuenow'],25);const buttons=nodes(tree).filter(n=>n.type==='button');buttons[0].props.onClick();buttons[1].props.onClick();assert.equal(retries,1);assert.equal(exits,1);});
 await test('fade starts only after scene readiness, lasts 260ms and is cleaned on exit',()=>{ui.reset(true);const ready={generation:1,phase:'ready',completed:44,total:44,error:''};let tree=screen(ready);assert.equal(tree.props.inert,true);assert(tree.props.className.includes('loading-ready'));const cleanup=ui.effects[0](),entry=[...timers].find(([,v])=>v.ms===LOADING_FADE_MS);assert(entry);entry[1].fn();assert.equal(screen(ready),null);cleanup();assert(!timers.has(entry[0]));tree=screen({...ready,generation:2,phase:'world'});assert(tree);tree=screen({...ready,generation:2});assert(tree,'new room must have its own fade');});
 const renderer=await import(project.module('renderer'));let active=true,drawn=0,created=0;globalThis.document={createElement:()=>{created++;return{width:0,height:0,getContext:()=>({fillRect(){drawn++;},beginPath(){},arc(){},fill(){}})}}};
 await test('map prewarming yields between row batches and never publishes a cancelled partial map',async()=>{await renderer.prepareWorldMap(async()=>{if(drawn)active=false;},()=>active);assert(drawn>0&&drawn<512*512);const before=drawn;renderer.worldMap();assert.equal(created,2);assert.equal(drawn-before,512*512);const complete=drawn;renderer.worldMap();assert.equal(drawn,complete);});
 console.log(`${checks} loading checks; 0 failures`);
}finally{clients.forEach(c=>c.destroy());for(const[k,v]of original)if(v)Object.defineProperty(globalThis,k,v);else delete globalThis[k];project.cleanup();}
