import assert from 'node:assert/strict';
import {writeFileSync,mkdirSync} from 'node:fs';
import {join} from 'node:path';
import {pathToFileURL} from 'node:url';
import {compileProject} from './test-support.mjs';
const project=compileProject({name:'minimap'}),globals=['document','window','requestAnimationFrame','cancelAnimationFrame','setInterval','clearInterval','performance'];
const original=new Map(globals.map(k=>[k,Object.getOwnPropertyDescriptor(globalThis,k)]));let checks=0;
try {
 function canvas(record=false){
  const trace=[],styles={};let result;const context=new Proxy({canvas:null,measureText:value=>({width:String(value).length*6})},{get:(target,key)=>key in target?target[key]:key in styles?styles[key]:(...args)=>{if(record)trace.push([key,...args.map(value=>value&&typeof value==='object'&&value._minimapCanvas?'canvas':value)]);},set:(target,key,value)=>{styles[key]=value;if(record&&key!=='canvas')trace.push(['set',key,value]);return true;}});
  result={_minimapCanvas:true,width:1,height:1,getContext:()=>context,trace};context.canvas=result;return result;
 }
 globalThis.document={createElement:()=>canvas()};
 const [mini,sim,world,structures]=await Promise.all(['minimap','simulation','world','structures'].map(name=>import(project.module(name))));
 const test=(name,fn)=>{fn();checks++;console.log('PASS',name);};
 const fixture=()=>{const state=sim.createWorld(100000);state.players={p:sim.createPlayer('p','secret','P',0,100000)};state.mobs=[];state.buildings={};state.plots={};return state;};
 const pos={...world.SPAWN,level:0,face:'up',moving:false};
 const paint=(state,point=pos)=>{const c=canvas(true);mini.paintMinimap(c,state,'p',point);return c;};
 test('player projection stays in the exact centre while world coordinates change',()=>{for(const point of [world.SPAWN,world.MINE.spawn,{x:1,y:510},{x:377.25,y:94.75}]){const p=mini.minimapProjection(point,point);assert.equal(p.x,mini.MINIMAP_SIZE/2);assert.equal(p.y,mini.MINIMAP_SIZE/2);assert.equal(p.edge,false);}});
 test('near targets retain cardinal directions and a consistent world scale',()=>{const points=[[5,0],[0,5],[-5,0],[0,-5]].map(([dx,dy])=>mini.minimapProjection(pos,{x:pos.x+dx,y:pos.y+dy}));assert(points.every(p=>!p.edge));assert(points[0].x>80&&points[0].y===80);assert(points[1].y>80&&points[1].x===80);assert(points[2].x<80&&points[2].y===80);assert(points[3].y<80&&points[3].x===80);assert.equal(points[0].x-80,80-points[2].x);assert.equal(points[1].y-80,80-points[3].y);});
 test('far targets clamp within the map border without losing their bearing',()=>{for(const [dx,dy] of [[1000,0],[0,1000],[-1000,0],[0,-1000],[800,-600],[-400,900]]){const p=mini.minimapProjection(pos,{x:pos.x+dx,y:pos.y+dy});assert.equal(p.edge,true);assert(p.x>=10&&p.x<=150&&p.y>=10&&p.y<=150);assert(Math.abs((p.x-80)*dy-(p.y-80)*dx)<1e-7);assert(Math.abs(p.angle-Math.atan2(dy,dx))<1e-7);}});
 test('surface mine entrance and deep-mine exit remain reachable as edge directions',()=>{const surface=mini.minimapProjection(world.SPAWN,world.CAVE_ENTRANCE),underground=mini.minimapProjection({x:world.MINE.x+44,y:18},world.MINE.exit);assert(surface.edge&&surface.x>80&&surface.y<80);assert(underground.edge&&underground.y>80);});
 test('minimap uses a sharp backing canvas and never mutates the game world',()=>{const state=fixture(),before=JSON.stringify(state),c=paint(state);assert(c.width>=mini.MINIMAP_SIZE*2);assert.equal(c.width,c.height);assert.equal(JSON.stringify(state),before);assert(c.trace.some(v=>v[0]==='set'&&v[1]==='imageSmoothingEnabled'&&v[2]===false));});
 test('predicted local position anchors the map even when the server player position lags',()=>{const state=fixture(),a=paint(state).trace;state.players.p.x-=3;state.players.p.y+=4;assert.deepEqual(paint(state).trace,a);});
 test('nearby teammate is displayed only in the same scene and on the same floor',()=>{const state=fixture(),base=paint(state).trace;state.players.q={...sim.createPlayer('q','secret','Q',1,100000),x:pos.x+8,y:pos.y+3};assert.notDeepEqual(paint(state).trace,base);state.players.q.level=1;assert.deepEqual(paint(state).trace,base);Object.assign(state.players.q,{...world.MINE.spawn,level:0});assert.deepEqual(paint(state).trace,base);});
 test('mine teammates stay separate from surface teammates after a scene transition',()=>{const point={...pos,...world.MINE.spawn},state=fixture(),base=paint(state,point).trace;state.players.q={...sim.createPlayer('q','secret','Q',1,100000),x:pos.x,y:pos.y};assert.deepEqual(paint(state,point).trace,base);Object.assign(state.players.q,{x:point.x+5,y:point.y-3});assert.notDeepEqual(paint(state,point).trace,base);});
 test('actual construction appears promptly and removal removes its marker',()=>{const state=fixture(),base=paint(state).trace,id=structures.buildingKey(265,326,'floor');state.buildings[id]={id,x:265,y:326,kind:'floor',level:0};assert.notDeepEqual(paint(state).trace,base);delete state.buildings[id];assert.deepEqual(paint(state).trace,base);});
 test('other-floor construction and ground crops do not leak onto upstairs plans',()=>{const point={...pos,level:1},state=fixture(),base=paint(state,point).trace,id=structures.buildingKey(265,326,'floor');state.buildings[id]={id,x:265,y:326,kind:'floor',level:0};state.plots['268:325']={x:268,y:325,crop:'carrot',progress:0,updated:100000,wetUntil:100000};assert.deepEqual(paint(state,point).trace,base);state.buildings[id].level=1;assert.notDeepEqual(paint(state,point).trace,base);});

 test('direction arrows remain visible at the top and bottom edges without status plates covering them',()=>{for(const [point,target] of [[pos,world.CAVE_ENTRANCE],[{...pos,x:world.MINE.x+44,y:18},world.MINE.exit]]){const guide=mini.minimapProjection(point,target),trace=paint(fixture(),point).trace,index=trace.findIndex(v=>v[0]==='rotate'&&v[1]===guide.angle),tip={x:guide.x+Math.cos(guide.angle)*4,y:guide.y+Math.sin(guide.angle)*4};assert(index>=0);for(const op of trace.slice(index+1))if(op[0]==='fillRect'){const[,x,y,w,h]=op;assert(!(tip.x>=x&&tip.x<=x+w&&tip.y>=y&&tip.y<=y+h),'a later status plate covers the destination arrow');}}});
 test('disconnected stale teammates disappear without hiding active teammates',()=>{const state=fixture(),base=paint(state).trace;state.players.q={...sim.createPlayer('q','secret','Q',1,100000),x:pos.x+8,y:pos.y+3,seen:84000};assert.deepEqual(paint(state).trace,base);state.players.q.seen=99900;assert.notDeepEqual(paint(state).trace,base);});
 // Execute the actual React component against deterministic hooks and timers.
 mkdirSync(join(project.temp,'components'),{recursive:true});const hostPath=join(project.temp,'components/minimap-host.mjs');
 writeFileSync(hostPath,`export const refs=[],effects=[],paints=[];let ri=0,ei=0;export function reset(clear=false){ri=ei=0;if(clear){refs.length=effects.length=paints.length=0;}}export function useRef(v){const i=ri++;return refs[i]??={current:v};}export function useEffect(fn,deps){effects[ei++]={fn,deps};}export function jsx(type,props,key){return{type,props:props||{},key};}export const jsxs=jsx;export function paintMinimap(...args){paints.push(args);}`);
 const host=await import(pathToFileURL(hostPath)),{default:Minimap}=await import(project.compileFile('components/Minimap.tsx',Object.fromEntries(['react','react/jsx-runtime','@/lib/minimap'].map(name=>[name,'./minimap-host.mjs']))));
 const timers=new Map();let timerId=0;
 globalThis.setInterval=(fn,delay)=>{timers.set(++timerId,{fn,delay});return timerId;};globalThis.clearInterval=id=>timers.delete(id);
 function componentFixture(props={}){host.reset(true);timers.clear();document.hidden=false;const game={connected:true,world:fixture(),session:{playerId:'p'},pos:{...pos},art:{}},client={current:game};let opened=0;const tree=Minimap({client,onOpen:()=>opened++,...props});if(tree)host.refs[0].current=canvas();return{game,client,tree,get opened(){return opened;}};}
 test('minimap mounts one 10 fps timer and paints immediately without a server request',()=>{const f=componentFixture(),cleanup=host.effects[0].fn();assert.equal(timers.size,1);const timer=[...timers.values()][0];assert.equal(timer.delay,100);assert.equal(host.paints.length,1);for(let i=0;i<10;i++)timer.fn();assert.equal(host.paints.length,11);assert.equal(host.paints.at(-1)[1],f.game.world);cleanup();assert.equal(timers.size,0);});
 test('each minimap update uses the current client prediction, including floor transitions',()=>{const f=componentFixture(),cleanup=host.effects[0].fn(),draw=[...timers.values()][0].fn;f.client.current={...f.game,world:fixture(),pos:{...pos,x:266,y:330,level:2}};draw();assert.equal(host.paints.at(-1)[1],f.client.current.world);assert.equal(host.paints.at(-1)[3],f.client.current.pos);assert.equal(host.paints.at(-1)[3].level,2);cleanup();});
 test('hidden dialogs render no map and create no background draw timer',()=>{const f=componentFixture({hidden:true});assert.equal(f.tree,null);assert.equal(host.effects[0].fn(),undefined);assert.equal(timers.size,0);assert.equal(host.paints.length,0);});
 test('background tabs and disconnected clients suspend minimap drawing',()=>{const f=componentFixture(),cleanup=host.effects[0].fn(),draw=[...timers.values()][0].fn;assert.equal(host.paints.length,1);document.hidden=true;draw();assert.equal(host.paints.length,1);document.hidden=false;f.game.connected=false;draw();assert.equal(host.paints.length,1);f.game.connected=true;f.game.session=null;draw();assert.equal(host.paints.length,1);f.game.session={playerId:'p'};draw();assert.equal(host.paints.length,2);cleanup();});
 test('unmount and development remount clean up timers without accumulating loops',()=>{componentFixture();const first=host.effects[0].fn();assert.equal(timers.size,1);first();assert.equal(timers.size,0);const second=host.effects[0].fn();assert.equal(timers.size,1);second();assert.equal(timers.size,0);});
 test('accessible map button opens the full map through its actual click handler',()=>{const f=componentFixture();assert.equal(f.tree.type,'button');assert(f.tree.props['aria-label'].includes('完整地图'));assert.equal(f.opened,0);f.tree.props.onClick();assert.equal(f.opened,1);});
 test('scene and coordinates update outside the drawing area, only when their text changes',()=>{const f=componentFixture();let label='',position='',writes=0;host.refs[1].current={get textContent(){return label;},set textContent(v){label=v;writes++;}};host.refs[2].current={get textContent(){return position;},set textContent(v){position=v;writes++;}};const cleanup=host.effects[0].fn(),draw=[...timers.values()][0].fn;assert.equal(label,'地表');assert.equal(position,'256, 320');assert.equal(writes,2);draw();assert.equal(writes,2);Object.assign(f.game.pos,world.MINE.spawn);draw();assert.equal(label,'矿洞');assert.equal(position,'48, 83');assert.equal(writes,4);Object.assign(f.game.pos,{...pos,level:2});draw();assert.equal(label,'3 层');assert.equal(position,'256, 320');cleanup();});
 console.log(`${checks} checks; 0 failures`);
} finally {for(const[k,v]of original)if(v)Object.defineProperty(globalThis,k,v);else delete globalThis[k];project.cleanup();}
